/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;

import controlador.GestionarInventario;
import exception.ProductoInvalidoException;
import javax.swing.JOptionPane;
import java.util.List;
import logica.*;

/**
 *
 * @author Nataly
 */
public class GestionInventario extends javax.swing.JFrame {

    private GestionarInventario gestionInventario;

    /**
     * Creates new form Tienda
     */
    public GestionInventario(GestionarInventario gestionInventario) {
        this.gestionInventario = gestionInventario;
        initComponents();
        configurarVentana();
    }

    private void configurarVentana() {
        this.setTitle("TechStore - Gestión de Inventario");
        this.setLocationRelativeTo(null); // Centrar en pantalla
        this.setResizable(false);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")                       
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInventario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarProducto = new javax.swing.JButton();
        btnNuevoProducto = new javax.swing.JButton();
        btnActualizarStock = new javax.swing.JButton();
        btnListaProductos = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnStockBajo = new javax.swing.JButton();
        btnProductoOferta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelInventario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 2, true));

        jLabel1.setFont(new java.awt.Font("MS PGothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Gestión de Inventario");

        btnBuscarProducto.setBackground(new java.awt.Color(204, 204, 255));
        btnBuscarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarProducto.setText("Buscar Producto");
        btnBuscarProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        btnNuevoProducto.setBackground(new java.awt.Color(204, 255, 204));
        btnNuevoProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevoProducto.setText("Nuevo Producto");
        btnNuevoProducto.setToolTipText("");
        btnNuevoProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });

        btnActualizarStock.setBackground(new java.awt.Color(204, 255, 204));
        btnActualizarStock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizarStock.setText(" Actualizar Stock");
        btnActualizarStock.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarStockActionPerformed(evt);
            }
        });

        btnListaProductos.setBackground(new java.awt.Color(204, 204, 255));
        btnListaProductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListaProductos.setText("Lista de Productos");
        btnListaProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnListaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaProductosActionPerformed(evt);
            }
        });

        btnAtras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(102, 102, 102));
        btnAtras.setLabel("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnEliminarProducto.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarProducto.setText("Eliminar Producto");
        btnEliminarProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        btnStockBajo.setBackground(new java.awt.Color(255, 204, 153));
        btnStockBajo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStockBajo.setText("Productos con Stock Bajo");
        btnStockBajo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStockBajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockBajoActionPerformed(evt);
            }
        });

        btnProductoOferta.setBackground(new java.awt.Color(204, 255, 204));
        btnProductoOferta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProductoOferta.setText("+ Producto en oferta");
        btnProductoOferta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProductoOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoOfertaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInventarioLayout = new javax.swing.GroupLayout(jPanelInventario);
        jPanelInventario.setLayout(jPanelInventarioLayout);
        jPanelInventarioLayout.setHorizontalGroup(
            jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInventarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
            .addGroup(jPanelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInventarioLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(btnNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProductoOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInventarioLayout.createSequentialGroup()
                        .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnStockBajo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(12, 12, 12))
            .addGroup(jPanelInventarioLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInventarioLayout.setVerticalGroup(
            jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProductoOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStockBajo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(527, 527, 527))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        // TODO add your handling code here:
        try {
            DialogoNuevoProducto dialogo = new DialogoNuevoProducto(this, true, gestionInventario);
            dialogo.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al abrir el formulario de nuevo producto:\n" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void btnActualizarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarStockActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog(this,
                "Ingrese el código de barras del producto:",
                "Actualizar Stock",
                JOptionPane.QUESTION_MESSAGE);

        if (codigo != null && !codigo.trim().isEmpty()) {
            try {
                // Ajusta este método al que realmente tengas en GestionarInventario
                ProductoBase producto = gestionInventario.buscarPorCodigoBarras(codigo.trim());

                if (producto == null || !(producto instanceof ProductoFisico)) {
                    JOptionPane.showMessageDialog(this,
                            "No se encontró un producto físico con ese código.",
                            "Producto no encontrado",
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }

                ProductoFisico pf = (ProductoFisico) producto;

                String cantidadStr = JOptionPane.showInputDialog(this,
                        "Producto: " + pf.getNombre() + "\n"
                        + "Stock actual: " + pf.getStockEnTienda() + "\n\n"
                        + "Ingrese la cantidad a agregar (positiva) o reducir (negativa):",
                        "Actualizar Stock",
                        JOptionPane.QUESTION_MESSAGE);

                if (cantidadStr != null && !cantidadStr.trim().isEmpty()) {
                    int cantidad = Integer.parseInt(cantidadStr.trim());
                    int nuevoStock = pf.getStockEnTienda() + cantidad;

                    if (nuevoStock < 0) {
                        JOptionPane.showMessageDialog(this,
                                "El stock no puede ser negativo.\n"
                                + "Stock actual: " + pf.getStockEnTienda() + "\n"
                                + "Cantidad solicitada: " + cantidad,
                                "Stock insuficiente",
                                JOptionPane.WARNING_MESSAGE);
                        return;
                    }

                    pf.setStockEnTienda(nuevoStock);
                    gestionInventario.guardarTodos();

                    JOptionPane.showMessageDialog(this,
                            "Stock actualizado correctamente.\n\n"
                            + "Producto: " + pf.getNombre() + "\n"
                            + "Stock anterior: " + (nuevoStock - cantidad) + "\n"
                            + "Cambio: " + (cantidad >= 0 ? "+" : "") + cantidad + "\n"
                            + "Stock nuevo: " + nuevoStock,
                            "Éxito",
                            JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "Por favor ingrese un número válido.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error al actualizar stock:\n" + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnActualizarStockActionPerformed

    private void btnProductoOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoOfertaActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog(this,
                "Ingrese el código de barras del producto físico:",
                "Producto en oferta",
                JOptionPane.QUESTION_MESSAGE);

        if (codigo != null && !codigo.trim().isEmpty()) {
            try {
                ProductoBase producto = gestionInventario.buscarPorCodigoBarras(codigo.trim());

                if (producto == null || !(producto instanceof ProductoFisico)) {
                    JOptionPane.showMessageDialog(this,
                            "No se encontró un producto físico con ese código.",
                            "Producto no encontrado",
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }

                ProductoFisico pf = (ProductoFisico) producto;

                String porcentajeStr = JOptionPane.showInputDialog(this,
                        "Producto: " + pf.getNombre() + "\n"
                        + "Precio actual: $" + String.format("%.2f", pf.getPrecio()) + "\n"
                        + "En oferta: " + (pf.isEnOferta() ? "Sí" : "No") + "\n\n"
                        + "Ingrese el porcentaje de descuento (0-100):",
                        "Configurar oferta",
                        JOptionPane.QUESTION_MESSAGE);

                if (porcentajeStr != null && !porcentajeStr.trim().isEmpty()) {
                    double porcentaje = Double.parseDouble(porcentajeStr.trim());

                    if (porcentaje < 0 || porcentaje > 100) {
                        JOptionPane.showMessageDialog(this,
                                "El porcentaje debe estar entre 0 y 100.",
                                "Porcentaje inválido",
                                JOptionPane.WARNING_MESSAGE);
                        return;
                    }

                    double descuentoDecimal = porcentaje / 100.0;
                    pf.setEnOferta(descuentoDecimal > 0, descuentoDecimal);
                    gestionInventario.guardarTodos();

                    double precioConDescuento = pf.calcularPrecioConDescuento();

                    JOptionPane.showMessageDialog(this,
                            "Oferta configurada correctamente.\n\n"
                            + "Producto: " + pf.getNombre() + "\n"
                            + "Precio original: $" + String.format("%.2f", pf.getPrecio()) + "\n"
                            + "Descuento: " + porcentaje + "%\n"
                            + "Precio final: $" + String.format("%.2f", precioConDescuento),
                            "Éxito",
                            JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "Por favor ingrese un número válido.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error al configurar oferta:\n" + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnProductoOfertaActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        // TODO add your handling code here:
        String criterio = JOptionPane.showInputDialog(this,
                "Ingrese el código de barras o nombre del producto:",
                "Buscar Producto",
                JOptionPane.QUESTION_MESSAGE);

        if (criterio != null && !criterio.trim().isEmpty()) {
            try {
                // 1) Buscar por código de barras
                ProductoBase producto = gestionInventario.buscarPorCodigoBarras(criterio.trim());

                if (producto != null) {
                    mostrarInformacionProducto(producto);
                } else {
                    // 2) Buscar por nombre
                    List<ProductoBase> productos = gestionInventario.buscarPorNombre(criterio.trim());

                    if (productos.isEmpty()) {
                        JOptionPane.showMessageDialog(this,
                                "No se encontró ningún producto con ese criterio.",
                                "Producto no encontrado",
                                JOptionPane.INFORMATION_MESSAGE);
                    } else if (productos.size() == 1) {
                        mostrarInformacionProducto(productos.get(0));
                    } else {
                        String[] opciones = new String[productos.size()];
                        for (int i = 0; i < productos.size(); i++) {
                            String codigoTexto = (productos.get(i) instanceof ProductoFisico)
                                    ? ((ProductoFisico) productos.get(i)).getCodigoDeBarras()
                                    : "(sin código físico)";
                            opciones[i] = productos.get(i).getNombre() + " - " + codigoTexto;
                        }

                        String seleccion = (String) JOptionPane.showInputDialog(this,
                                "Se encontraron varios productos. Seleccione uno:",
                                "Seleccionar Producto",
                                JOptionPane.QUESTION_MESSAGE,
                                null,
                                opciones,
                                opciones[0]);

                        if (seleccion != null) {
                            int indice = java.util.Arrays.asList(opciones).indexOf(seleccion);
                            mostrarInformacionProducto(productos.get(indice));
                        }
                    }
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error al buscar producto:\n" + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnListaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaProductosActionPerformed
        // TODO add your handling code here:
        try {
            List<ProductoBase> productos = gestionInventario.obtenerTodosLosProductos();

            if (productos.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No hay productos registrados en el inventario.",
                        "Inventario vacío",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            StringBuilder lista = new StringBuilder();
            lista.append("====\n");
            lista.append("    LISTA DE PRODUCTOS\n");
            lista.append("====\n\n");

            int contadorFisicos = 0;
            int contadorDigitales = 0;

            lista.append("--- PRODUCTOS FÍSICOS ---\n");
            for (ProductoBase producto : productos) {
                if (producto instanceof ProductoFisico) {
                    ProductoFisico pf = (ProductoFisico) producto;
                    lista.append("• ").append(pf.getNombre()).append("\n");
                    lista.append("  Código: ").append(pf.getCodigoDeBarras()).append("\n");
                    lista.append("  Precio: $").append(String.format("%.2f", pf.getPrecio()));
                    if (pf.isEnOferta()) {
                        lista.append(" (").append(pf.getDescuentoPorcentaje() * 100).append("% OFF)");
                    }
                    lista.append("\n");
                    lista.append("  Stock: ").append(pf.getStockEnTienda()).append("\n\n");
                    contadorFisicos++;
                }
            }

            lista.append("\n--- SERVICIOS DIGITALES ---\n");
            for (ProductoBase producto : productos) {
                if (producto instanceof ServicioDigital) {
                    ServicioDigital sd = (ServicioDigital) producto;
                    lista.append("• ").append(sd.getNombre()).append("\n");
                    lista.append("  Categoría: ").append(sd.getCategoria()).append("\n");
                    lista.append("  Precio: $").append(String.format("%.2f", sd.getPrecio())).append("\n");
                    lista.append("  Duración estimada: ").append(sd.getDuracionEstimadaMinutos()).append(" minutos\n\n");
                    contadorDigitales++;
                }
            }

            lista.append("====\n");
            lista.append("Total Productos Físicos: ").append(contadorFisicos).append("\n");
            lista.append("Total Servicios Digitales: ").append(contadorDigitales).append("\n");
            lista.append("TOTAL: ").append(productos.size()).append(" productos\n");
            lista.append("====\n");

            JOptionPane.showMessageDialog(this,
                    lista.toString(),
                    "Lista de Productos",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al listar productos:\n" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnListaProductosActionPerformed

    private void btnStockBajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockBajoActionPerformed
        // TODO add your handling code here:
        try {
            // Ajusta este método al que tengas en GestionarInventario
            List<ProductoFisico> productosBajoStock = gestionInventario.obtenerProductosStockBajo();

            if (productosBajoStock.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No hay productos con stock bajo.\n"
                        + "Todos los productos tienen stock suficiente.",
                        "Stock adecuado",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            StringBuilder alerta = new StringBuilder();
            alerta.append("====\n");
            alerta.append("   ALERTA: PRODUCTOS CON STOCK BAJO\n");
            alerta.append("====\n\n");

            for (ProductoFisico producto : productosBajoStock) {
                alerta.append("• ").append(producto.getNombre()).append("\n");
                alerta.append("  Código: ").append(producto.getCodigoDeBarras()).append("\n");
                alerta.append("  Stock actual: ").append(producto.getStockEnTienda());

                int s = producto.getStockEnTienda();
                if (s == 0) {
                    alerta.append(" (AGOTADO)");
                } else if (s <= 5) {
                    alerta.append(" (CRÍTICO)");
                } else {
                    alerta.append(" (BAJO)");
                }
                alerta.append("\n\n");
            }

            alerta.append("====\n");
            alerta.append("Total productos con stock bajo: ").append(productosBajoStock.size()).append("\n");
            alerta.append("====\n");

            JOptionPane.showMessageDialog(this,
                    alerta.toString(),
                    "Productos con stock bajo",
                    JOptionPane.WARNING_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al consultar stock:\n" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnStockBajoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog(this,
                "Ingrese el código de barras del producto a eliminar:",
                "Eliminar Producto",
                JOptionPane.QUESTION_MESSAGE);

        if (codigo != null && !codigo.trim().isEmpty()) {
            try {
                // Ajusta al método real en GestionarInventario
                ProductoBase producto = gestionInventario.buscarPorCodigoBarras(codigo.trim());

                if (producto == null) {
                    JOptionPane.showMessageDialog(this,
                            "No se encontró ningún producto con ese código.",
                            "Producto no encontrado",
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }

                int confirmacion = JOptionPane.showConfirmDialog(this,
                        "¿Está seguro de eliminar este producto?\n\n"
                        + "Nombre: " + producto.getNombre() + "\n"
                        + "Categoría: " + producto.getCategoria() + "\n"
                        + "Precio: $" + String.format("%.2f", producto.getPrecio()) + "\n\n"
                        + "Esta acción no se puede deshacer.",
                        "Confirmar eliminación",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE);

                if (confirmacion == JOptionPane.YES_OPTION) {
                    boolean eliminado = gestionInventario.eliminarProducto(codigo.trim());

                    if (eliminado) {
                        JOptionPane.showMessageDialog(this,
                                "Producto eliminado correctamente.",
                                "Éxito",
                                JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "No se pudo eliminar el producto.",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                    }
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error al eliminar producto:\n" + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void mostrarInformacionProducto(ProductoBase producto) {
        StringBuilder info = new StringBuilder();
        info.append("====\n");
        info.append("    INFORMACIÓN DEL PRODUCTO\n");
        info.append("====\n\n");
        info.append("Nombre: ").append(producto.getNombre()).append("\n");
        info.append("Categoría: ").append(producto.getCategoria()).append("\n");
        info.append("Precio base: $").append(String.format("%.2f", producto.getPrecio())).append("\n");

        if (producto instanceof ProductoFisico) {
            ProductoFisico pf = (ProductoFisico) producto;
            info.append("\nTipo: Producto Físico\n");
            info.append("Código de barras: ").append(pf.getCodigoDeBarras()).append("\n");
            info.append("Stock en tienda: ").append(pf.getStockEnTienda()).append("\n");
            info.append("Ubicación: ").append(pf.getUbicacion()).append("\n");

            if (pf.isEnOferta()) {
                info.append("En oferta: Sí (")
                        .append(pf.getDescuentoPorcentaje() * 100)
                        .append("% OFF)\n");
                info.append("Precio con descuento: $")
                        .append(String.format("%.2f", pf.calcularPrecioConDescuento()))
                        .append("\n");
            } else {
                info.append("En oferta: No\n");
            }

        } else if (producto instanceof ServicioDigital) {
            ServicioDigital sd = (ServicioDigital) producto;
            info.append("\nTipo: Servicio Digital\n");
            info.append("Duración estimada: ")
                    .append(sd.getDuracionEstimadaMinutos())
                    .append(" minutos\n");
            info.append("Descripción: ").append(sd.getDescripcion()).append("\n");
        }

        info.append("\n====\n");

        JOptionPane.showMessageDialog(this,
                info.toString(),
                "Información del producto",
                JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionInventario(new controlador.GestionarInventario()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarStock;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnListaProductos;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JButton btnProductoOferta;
    private javax.swing.JButton btnStockBajo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelInventario;
    // End of variables declaration//GEN-END:variables
}
